name: 'durable_transport'
services:
  durable-streams:
    build:
      context: .
      dockerfile: Dockerfile.durable-streams
    ports:
      - 4437:4437
    volumes:
      - durable-streams-data:/app/data

volumes:
  durable-streams-data:
