/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionIdUsernameRouteImport } from './routes/chat.$sessionId.$username'
import { Route as ApiChatOscarRouteImport } from './routes/api.chat.oscar'
import { Route as ApiChatKermitRouteImport } from './routes/api.chat.kermit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdUsernameRoute = ChatSessionIdUsernameRouteImport.update({
  id: '/chat/$sessionId/$username',
  path: '/chat/$sessionId/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatOscarRoute = ApiChatOscarRouteImport.update({
  id: '/api/chat/oscar',
  path: '/api/chat/oscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatKermitRoute = ApiChatKermitRouteImport.update({
  id: '/api/chat/kermit',
  path: '/api/chat/kermit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat/kermit': typeof ApiChatKermitRoute
  '/api/chat/oscar': typeof ApiChatOscarRoute
  '/chat/$sessionId/$username': typeof ChatSessionIdUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat/kermit': typeof ApiChatKermitRoute
  '/api/chat/oscar': typeof ApiChatOscarRoute
  '/chat/$sessionId/$username': typeof ChatSessionIdUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat/kermit': typeof ApiChatKermitRoute
  '/api/chat/oscar': typeof ApiChatOscarRoute
  '/chat/$sessionId/$username': typeof ChatSessionIdUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/chat/kermit'
    | '/api/chat/oscar'
    | '/chat/$sessionId/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/chat/kermit'
    | '/api/chat/oscar'
    | '/chat/$sessionId/$username'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/chat/kermit'
    | '/api/chat/oscar'
    | '/chat/$sessionId/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiChatKermitRoute: typeof ApiChatKermitRoute
  ApiChatOscarRoute: typeof ApiChatOscarRoute
  ChatSessionIdUsernameRoute: typeof ChatSessionIdUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId/$username': {
      id: '/chat/$sessionId/$username'
      path: '/chat/$sessionId/$username'
      fullPath: '/chat/$sessionId/$username'
      preLoaderRoute: typeof ChatSessionIdUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/oscar': {
      id: '/api/chat/oscar'
      path: '/api/chat/oscar'
      fullPath: '/api/chat/oscar'
      preLoaderRoute: typeof ApiChatOscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/kermit': {
      id: '/api/chat/kermit'
      path: '/api/chat/kermit'
      fullPath: '/api/chat/kermit'
      preLoaderRoute: typeof ApiChatKermitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiChatKermitRoute: ApiChatKermitRoute,
  ApiChatOscarRoute: ApiChatOscarRoute,
  ChatSessionIdUsernameRoute: ChatSessionIdUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
